#!/bin/sh
WHERE=$((RANDOM))$((RANDOM))
mkdir -p trash/$WHERE
find . -name \*.a -print -exec mv -f {} trash/$WHERE \;
find . -name \*.o -print -exec mv -f {} trash/$WHERE \;
find . -name \*.exe -print -exec mv -f {} trash/$WHERE \;
find . -name \*.dSYM -print -exec mv -f {} trash/$WHERE \;
